### ISSUE TITLE
Allow comments in Docusaurus with Giscus and GitHub Discussion

### ISSUE THREAD

**Issue by Nils98Ar** [osism/osism.github.io#294]
Allow visitors to leave comments below articles for low-threshold feedback and improvement suggestions.

See:
https://dev.to/m19v/how-to-add-giscus-comments-to-docusaurus-439h

**Comment by Nils98Ar** [comment]
It would be ideal to create one discussion per article as soon as the first comment is created in my opinion.

**Comment by berendt** [comment]
What is the added value compared to issues?

**Comment by Nils98Ar** [comment]
That it is directly available in Docusaurus and you can start writing directly below the article.

I think many people would not go to GitHub and open an issue but maybe they would leave a comment below the article which could be turned into an issue.

**Comment by berendt** [comment]
Take it with you to the SCS Call on Wednesday. This then needs to be moderated etc. I think there are enough ways to ask and we don't need to add another way.

**Comment by Nils98Ar** [comment]
My idea was to make it as easy as possible to keep the docs up-to-date.

**Comment by berendt** [comment]
Feel free to discuss it on Wednesday. I don't see much benefit in it. The more channels are open, the more effort it takes to monitor everything and respond in a meaningful way.

**Comment by Nils98Ar** [comment]
Okay, but to make it clear: I thought about feedback and improvement suggestions and not about support questions ;)

**Comment by Nils98Ar** [comment]
Maybe an „Open issue“ button would be better then.
