### ISSUE TITLE
Clicking „Edit this page“ in Docusaurus should open „Edit in place“ in Github

### ISSUE THREAD

**Issue by Nils98Ar** [osism/osism.github.io#295]
Currently only the file is opened in GitHub, not the editor directly.

**Comment by berendt** [comment]
This requires that you are logged in.  Therefore, only the MD files themselves are displayed on Github.

**Comment by Nils98Ar** [comment]
I would assume that not logged in users are redirected to the login page and then to the editor afterwards?

I think if you click „Edit this page“ you want to edit the page and you need to login to GitHub anyway.

**Comment by berendt** [comment]
There are two use cases. You want to know what the file is called and edit it locally with the editor of your choice or you really want to edit the file with the Github editor. The first case is much more common.

**Comment by Nils98Ar** [comment]
Ah okay I did not think about this case.
