### ISSUE TITLE
osism apply docker issues

### ISSUE THREAD

**Issue by Nils98Ar** [osism/osism.github.io#57]
Doesn't this stop the `osism apply` when executed for the manager? Maybe the playbook shouldn't be rolled out for all nodes at once?

https://github.com/osism/osism.github.io/blob/c118e3ab39c864819dfa605e6de71f4275b0fb16/docs/guides/upgrade-guides/docker.md?plain=1#L53

This was the behaviour:

```
TASK [osism.services.docker : Install docker-cli package] **********************
changed: [manager01.aov.cloud]
- osism apply facts && osism apply configuration && osism reconciler sync

TASK [osism.services.docker : Install docker package] **************************
Connection closed by server.
```

Now the `osism apply docker` does not return any output and according to ara nothing is started. It stucks at `gather_facts` and also an `osism apply facts`, `docker compose down` and `up -d` or a reboot of the manager node does not help.
```
dragon@manager01:~$ osism apply docker -vvvv
reading /root/.cache/python-entrypoints/292f087004bf5eb310697011fda9397673e6f3f3dbe3f68a4fc726cef2eabea8

def run(self, environment, playbook, arguments, publish=0, locking=1):
    return 1


def gather_facts(self, publish=0):
    return 1
```

**Comment by Nils98Ar** [comment]
Maybe we have to delete some cache in a docker volume?

**Comment by Nils98Ar** [comment]
`docker logs -f osism-ansible` says:
```
[2023-10-05 18:31:35,165: INFO/MainProcess] Task osism.tasks.ansible.run[b5eb9f29-7081-4d2c-a486-c22988632be8] received
2023-10-05 18:31:35.177 | INFO     | osism.tasks:run_ansible_in_environment:68 - worker = osism-ansible, environment = generic, role = docker
[2023-10-05 18:31:35,180: INFO/ForkPoolWorker-2] Registering Redlock._acquired_script
[2023-10-05 18:31:35,181: INFO/ForkPoolWorker-2] Registering Redlock._extend_script
[2023-10-05 18:31:35,182: INFO/ForkPoolWorker-2] Registering Redlock._release_script
```

**Comment by Nils98Ar** [comment]
dragon@manager01:/opt/configuration$ osism task list
+----------------------+--------------------------------------+-------------------------+----------+----------------------------+---------------------------+
| Worker               | ID                                   | Name                    | Status   | Start time                 | Arguments                 |
|----------------------+--------------------------------------+-------------------------+----------+----------------------------+---------------------------|
| celery@osism-ansible | b5eb9f29-7081-4d2c-a486-c22988632be8 | osism.tasks.ansible.run | ACTIVE   | 2023-10-05 18:31:35.167387 | ['generic', 'docker', []] |
| celery@osism-ansible | 2387c3d1-d265-437b-87ea-a0c68f783613 | osism.tasks.ansible.run | ACTIVE   | 2023-10-05 18:30:55.366417 | ['generic', 'docker', []] |
+----------------------+--------------------------------------+-------------------------+----------+----------------------------+---------------------------+

**Comment by berendt** [comment]
Yes makes sense not to update the Docker from the manager itself with the manager. There will soon be a osism update docker command similar to the osism update manager that you can use to do this.

The hanging tasks can currently only be deleted directly from the Reids or alternatively delete the Redis service from the manager + the associated volume and then run osism update manager.

**Comment by Nils98Ar** [comment]
We will try this!

Our idea was to exactly follow the instructions in new documentation and test ist ;)

**Comment by berendt** [comment]
Any input is welcome. Thanks for the test.

**Comment by Nils98Ar** [comment]
Thank you for the quick answer + fix!

This helped to get `osism apply docker -l 'docker:!manager'` running:
```
cd /opt/manager
docker-compose down
docker volume rm manager_redis
docker-compose up -d
```
