### ISSUE TITLE
ANSIBLE_VAULT_PASSWORD_FILE still needed?

### ISSUE THREAD

**Issue by Nils98Ar** [osism/osism.github.io#64]
We still need to provide the vaulpass file via `ANSIBLE_VAULT_PASSWORD_FILE` for the `osism-update-manager` command.

Should this be added to the docs or is there another way to provide the vaultpass now?

https://github.com/osism/osism.github.io/blob/5b6041e77de167bc2bd47e8c24dae23e2ad9fb5f/docs/guides/upgrade-guides/manager.md?plain=1#L45

**Comment by berendt** [comment]
If you use a vault pass file you have to set this parameter.

**Comment by Nils98Ar** [comment]
I overlooked the `--ask-vault-pass` hint.
