### ISSUE TITLE
What is `ceph-rgw`?

### ISSUE THREAD

**Issue by killermoehre** [osism/osism.github.io#97]
Currently, deploying Rados-GW and using https://osism.github.io/docs/guides/deploy-guide/ceph as guide.

What is the `ceph-rgw` playbook? It either does nothing or doesn't exist.

https://github.com/osism/osism.github.io/blob/a502fec27be93120ff22fa3d8f01d401d7a6444b/docs/guides/deploy-guide/ceph.md?plain=1#L50

**Comment by berendt** [comment]
It's kolla-ceph-rgw.
